import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
	VERSION_SYNC_PACKAGE_GLOBS,
	collectCargoLockMismatches,
	findCargoLockPackageVersion,
	resolveWorkspaceProtocols,
	syncSignetNativeOptionalDependencies,
} from "./version-sync";

describe("version-sync", () => {
	test("keeps web workspace manifests out of Signet release version sync", () => {
		expect(VERSION_SYNC_PACKAGE_GLOBS).not.toContain("web/**/package.json");
	});

	test("reads local package versions from Cargo.lock entries", () => {
		const lock = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "signet-daemon"
version = "0.82.5"
dependencies = [
 "signet-core",
]
`;

		expect(findCargoLockPackageVersion(lock, "signet-daemon")).toBe("0.82.5");
		expect(findCargoLockPackageVersion(lock, "signet-native")).toBeNull();
	});

	test("resolves publishable runtime workspace protocols without rewriting dev-only workspace links", () => {
		const root = mkdtempSync(join(tmpdir(), "signet-version-sync-publish-"));
		try {
			const manifest = join(root, "package.json");
			writeFileSync(
				manifest,
				JSON.stringify(
					{
						name: "@signetai/test-publishable",
						version: "0.1.0",
						dependencies: { "@signet/runtime": "workspace:*" },
						optionalDependencies: { "@signet/optional": "workspace:^" },
						peerDependencies: { "@signet/peer": "workspace:~" },
						devDependencies: { "@signet/core": "workspace:*", "@signet/sdk": "workspace:*" },
						publishConfig: { access: "public" },
					},
					null,
					2,
				),
			);

			expect(resolveWorkspaceProtocols([manifest], "0.115.2", false)).toEqual([manifest]);
			const updated = JSON.parse(readFileSync(manifest, "utf8")) as {
				dependencies: Record<string, string>;
				optionalDependencies: Record<string, string>;
				peerDependencies: Record<string, string>;
				devDependencies: Record<string, string>;
			};
			expect(updated.dependencies["@signet/runtime"]).toBe("0.115.2");
			expect(updated.optionalDependencies["@signet/optional"]).toBe("^0.115.2");
			expect(updated.peerDependencies["@signet/peer"]).toBe("~0.115.2");
			expect(updated.devDependencies["@signet/core"]).toBe("workspace:*");
			expect(updated.devDependencies["@signet/sdk"]).toBe("workspace:*");
		} finally {
			rmSync(root, { force: true, recursive: true });
		}
	});

	test("syncs exact native optional package versions for the Signet wrapper", () => {
		const root = mkdtempSync(join(tmpdir(), "signet-version-sync-native-"));
		try {
			const manifest = join(root, "package.json");
			writeFileSync(
				manifest,
				JSON.stringify(
					{
						name: "signetai",
						version: "0.1.0",
						optionalDependencies: {
							"@signetai/signetai-linux-x64": "0.1.0",
							"@signetai/signetai-darwin-arm64": "0.1.0",
							"@other/package": "1.0.0",
						},
						publishConfig: { access: "public" },
					},
					null,
					2,
				),
			);

			expect(syncSignetNativeOptionalDependencies("0.115.2", false, manifest)).toEqual([manifest]);
			const updated = JSON.parse(readFileSync(manifest, "utf8")) as {
				optionalDependencies: Record<string, string>;
			};
			expect(updated.optionalDependencies["@signetai/signetai-linux-x64"]).toBe("0.115.2");
			expect(updated.optionalDependencies["@signetai/signetai-darwin-arm64"]).toBe("0.115.2");
			expect(updated.optionalDependencies["@other/package"]).toBe("1.0.0");
		} finally {
			rmSync(root, { force: true, recursive: true });
		}
	});

	test("flags stale Cargo.lock versions for workspace packages", () => {
		const root = mkdtempSync(join(tmpdir(), "signet-version-sync-"));
		try {
			const workspace = join(root, "platform", "daemon-rs");
			const crateDir = join(workspace, "crates", "signet-daemon");
			const crate = join(crateDir, "Cargo.toml");
			mkdirSync(crateDir, { recursive: true });
			writeFileSync(
				join(workspace, "Cargo.toml"),
				`[workspace.package]
version = "0.115.1"
`,
			);
			writeFileSync(
				crate,
				`[package]
name = "signet-daemon"
version.workspace = true
`,
			);
			writeFileSync(
				join(workspace, "Cargo.lock"),
				`version = 4

[[package]]
name = "signet-daemon"
version = "0.82.5"
`,
			);

			expect(collectCargoLockMismatches([crate], "0.115.1")).toEqual([
				`${join(workspace, "Cargo.lock")} package signet-daemon (0.82.5)`,
			]);
		} finally {
			rmSync(root, { force: true, recursive: true });
		}
	});
});
