import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { VERSION_SYNC_PACKAGE_GLOBS, collectCargoLockMismatches, findCargoLockPackageVersion } from "./version-sync";

describe("version-sync", () => {
	test("keeps web workspace manifests out of Signet release version sync", () => {
		expect(VERSION_SYNC_PACKAGE_GLOBS).not.toContain("web/**/package.json");
	});

	test("reads local package versions from Cargo.lock entries", () => {
		const lock = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "signet-daemon"
version = "0.82.5"
dependencies = [
 "signet-core",
]
`;

		expect(findCargoLockPackageVersion(lock, "signet-daemon")).toBe("0.82.5");
		expect(findCargoLockPackageVersion(lock, "signet-native")).toBeNull();
	});

	test("flags stale Cargo.lock versions for workspace packages", () => {
		const root = mkdtempSync(join(tmpdir(), "signet-version-sync-"));
		try {
			const workspace = join(root, "platform", "daemon-rs");
			const crateDir = join(workspace, "crates", "signet-daemon");
			const crate = join(crateDir, "Cargo.toml");
			mkdirSync(crateDir, { recursive: true });
			writeFileSync(
				join(workspace, "Cargo.toml"),
				`[workspace.package]
version = "0.115.1"
`,
			);
			writeFileSync(
				crate,
				`[package]
name = "signet-daemon"
version.workspace = true
`,
			);
			writeFileSync(
				join(workspace, "Cargo.lock"),
				`version = 4

[[package]]
name = "signet-daemon"
version = "0.82.5"
`,
			);

			expect(collectCargoLockMismatches([crate], "0.115.1")).toEqual([
				`${join(workspace, "Cargo.lock")} package signet-daemon (0.82.5)`,
			]);
		} finally {
			rmSync(root, { force: true, recursive: true });
		}
	});
});
