use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use hmac::{Hmac, Mac};
use sha2::Sha256;

const PASSWORD_HASH_PREFIX: &str = "pbkdf2-sha256";
const MIN_ITERATIONS: u32 = 10_000;
const MAX_ITERATIONS: u32 = 1_000_000;
const KEY_LENGTH: usize = 32;

type HmacSha256 = Hmac<Sha256>;

pub fn verify_plain_password(password: &str, expected: &str) -> bool {
    constant_time_eq(password.as_bytes(), expected.as_bytes())
}

pub fn verify_password_hash(password: &str, stored_hash: &str) -> bool {
    let mut parts = stored_hash.split('$');
    let (Some(prefix), Some(iterations), Some(salt), Some(expected), None) = (
        parts.next(),
        parts.next(),
        parts.next(),
        parts.next(),
        parts.next(),
    ) else {
        return false;
    };
    if prefix != PASSWORD_HASH_PREFIX {
        return false;
    }
    let Ok(iterations) = iterations.parse::<u32>() else {
        return false;
    };
    if !(MIN_ITERATIONS..=MAX_ITERATIONS).contains(&iterations) {
        return false;
    }
    let Ok(salt) = URL_SAFE_NO_PAD.decode(salt.as_bytes()) else {
        return false;
    };
    let Ok(expected) = URL_SAFE_NO_PAD.decode(expected.as_bytes()) else {
        return false;
    };
    if salt.len() < 8 || expected.len() != KEY_LENGTH {
        return false;
    }
    let actual = pbkdf2_hmac_sha256(password.as_bytes(), &salt, iterations, expected.len());
    constant_time_eq(&actual, &expected)
}

pub(crate) fn pbkdf2_hmac_sha256(
    password: &[u8],
    salt: &[u8],
    iterations: u32,
    dk_len: usize,
) -> Vec<u8> {
    let h_len = 32usize;
    let blocks = dk_len.div_ceil(h_len);
    let mut out = Vec::with_capacity(blocks * h_len);
    for block_index in 1..=blocks {
        let mut mac = HmacSha256::new_from_slice(password).expect("HMAC accepts any key length");
        mac.update(salt);
        mac.update(&(block_index as u32).to_be_bytes());
        let mut u = mac.finalize().into_bytes().to_vec();
        let mut t = u.clone();
        for _ in 1..iterations {
            let mut mac =
                HmacSha256::new_from_slice(password).expect("HMAC accepts any key length");
            mac.update(&u);
            u = mac.finalize().into_bytes().to_vec();
            for (dst, src) in t.iter_mut().zip(u.iter()) {
                *dst ^= *src;
            }
        }
        out.extend_from_slice(&t);
    }
    out.truncate(dk_len);
    out
}

fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verifies_known_pbkdf2_hash() {
        // Generated by TS hashPassword("correct horse battery staple", 10000).
        let hash = "pbkdf2-sha256$10000$YWJjZGVmZ2hpamtsbW5vcA$DIskV6toASr80zCtPVeCG3APSUi4JVudd_NeFhCnFxk";
        assert!(verify_password_hash("correct horse battery staple", hash));
        assert!(!verify_password_hash("wrong", hash));
    }
}
